<a href="https://colab.research.google.com/github/x200168shen/Cookbook-for-Rustaceans-in-Finance/blob/main/BERAS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
demoDate = np.array( [[1,2,3,4],[5,6,7,8],[9,10,11,12]])
newDate = np.reshape(demoDate,(6,2))
print(newDate)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [6]:
from tensorflow.keras.datasets import mnist
(samples_train, labels_train), (samples_test, labels_test) = \
   mnist.load_data()

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


MNIST集是 Keras 提供的。我们导入 mnist 模块，然后使用其定义的 load_data() 返回1训练集和1测试集,注意\后面没有空格，然后开始下载集，并存到磁盘上，速度很快

In [7]:
print("samples_train shape = ",samples_train.shape)
print("labels_train shape = ",labels_train.shape)
print("samples_test shape = ",samples_test.shape)
print("labels_test shape = ",labels_test.shape)

samples_train shape =  (60000, 28, 28)
labels_train shape =  (60000,)
samples_test shape =  (10000, 28, 28)
labels_test shape =  (10000,)


第一对变量 samples_train 和 labels_train 保存了包含训练集的 60,000
张图像及其对应的整数标签的数组。第二对变量 samples_test 和 labels_test 保存了包含测试集的 10,000 张图像和标签的数组。打印它们来快速查看它们的形状。这些数组都是从 Keras 返回的 NumPy 数组，因此它们都具有我们可以打印的内置 shape 属性。array（）的作用，6000逗号表示是列表而不是数字

In [8]:
from tensorflow.keras.datasets import mnist
(X_train, y_train), (X_test, y_test) = \
   mnist.load_data()

惯例是使用大写字母 X 来指代数据集的样本，使用小写字母 y 来指代其标签,加载 MNIST 数据，使用 X 作为样本，y 作为标签

In [10]:
image_height = X_train.shape[1]
image_width = X_train.shape[2]
number_of_pixels = image_height * image_width

因此让我们将每幅图像的原始高度和宽度存储在一个
变量中。我们还将它们相乘并将其保存为每幅图像的总像素数,这
种更通用的方法将使以后复制此代码并使其适应新的数据集变得更容易

In [11]:
print('start of y_train:', y_train[:15])

start of y_train: [5 0 4 1 9 2 1 3 1 4 3 5 3 6 1]


数据集中前15个元素

图像匹配。
由于 MNIST 数据非常知名，我们可以就此停止，但对于不太熟悉的数据集，我们可
能需要在整个数据中进行至少几次这样的抽查，以确保两个列表保持同步

In [12]:
X_train[0, 5:12, 5:12]

array([[  0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,  30,  36,  94, 154],
       [  0,   0,  49, 238, 253, 253, 253],
       [  0,   0,  18, 219, 253, 253, 253],
       [  0,   0,   0,  80, 156, 107, 253],
       [  0,   0,   0,   0,  14,   1, 154],
       [  0,   0,   0,   0,   0,   0, 139]], dtype=uint8)

末尾的变量 dtype 告诉我们这是一个 NumPy 数组，由数据类型 uint8 表示，这意味
着一个无符号的 8 位整数。检查 X_test 会发现相同的结构。正如我们从灰度图像数
据中预期的那样，所有值都在 0 到 255 之间

In [13]:
y_train[:15]


array([5, 0, 4, 1, 9, 2, 1, 3, 1, 4, 3, 5, 3, 6, 1], dtype=uint8)

无符号 8 位整数的 1D NumPy 数组，对于训练标签来说非常严格，
因为这些数字不能超过 255。但这里我们只存储标签 0 到 9，所以 0 到 255 的范围足
够了。

In [14]:
from sklearn.model_selection import train_test_split
 X_train, X_test, y_train, y_test  = \
  train_test_split(samples, labels, test_size=0.25)

IndentationError: unexpected indent (<ipython-input-14-1d952da058f1>, line 2)

In [18]:
from tensorflow.keras import backend as keras_backend
X_train = keras_backend.cast_to_floatx(X_train)
X_test = keras_backend.cast_to_floatx(X_test)

遍历每个条目并将其转换为我们所需的数据类型,Keras 后端的 cast_to_floatx() 函数，该函数以张量为参数，并将该张量的每个元素转换为 floatx 当前值指定的类型。该例程甚至不关心张量的形状。从一维列表到一些巨大的

我们知道训练和测试数据中的像素范围是 [0, 255]。我们想要的是以相同的方式重新
缩放所有像素，将它们从 [0, 255] 范围压缩到 [0,1] 范围。从概念上讲，这就像将毫
米测量单位转换为公里测量单位，反之亦然。
我们可以使用 Numpy 的 interp() 例程来缩放输入数据，该例程就是为这项工作而设计的。它需要一个数组（或张量）、一个输入范围和一个输出范围,将所有像素除以255.0来实现同样的事情

In [15]:
import numpy as np
X_train = np.interp(X_train, [0, 255], [0,1])
X_test = np.interp(X_test, [0, 255], [0,1])
X_train /= 255.0
X_test /= 255.0

X_train 和 X_test 中的特征数据最初由 0 到 255 范围内的
整数组成，这是图像数据通道的常见范围。我们刚刚将这些值转换为 32 位浮点
数，因此我们可以说它们现在在 0.0 到 255.0 范围内。
我们上面说过，我们需要将数据标准化到 [0.0, 1.0] 范围内。有助于正则化并延迟过度拟合的发生。如果我们使用像 S 型这样的激活函数，它可以防止我们的函数饱和。检查训练数据中像素的值，构建一个转换以将它们缩放到 [0,1]，然后将该转换应用于训练数据、测试数据和任何未来数据。我们可以创建一个 scikit-learn 的转换对象，对其进行训练，然后
将其应用于我们的数据。

In [27]:
from tensorflow.keras.utils import to_categorical
# 打印原始y_train 数组的前 5 个条目
y_train[:5]
# 将数组编码为独热列表
y_train = to_categorical(y_train)
# 打印的新前5个条目的独热编码形式
y_train[:5]

array([[[[[[[[[1., 0.],
              [0., 1.]],

             [[0., 1.],
              [1., 0.]]],


            [[[0., 1.],
              [1., 0.]],

             [[1., 0.],
              [0., 1.]]]],



           [[[[0., 1.],
              [1., 0.]],

             [[1., 0.],
              [0., 1.]]],


            [[[1., 0.],
              [0., 1.]],

             [[0., 1.],
              [1., 0.]]]]],




          [[[[[0., 1.],
              [1., 0.]],

             [[1., 0.],
              [0., 1.]]],


            [[[1., 0.],
              [0., 1.]],

             [[0., 1.],
              [1., 0.]]]],



           [[[[1., 0.],
              [0., 1.]],

             [[0., 1.],
              [1., 0.]]],


            [[[0., 1.],
              [1., 0.]],

             [[1., 0.],
              [0., 1.]]]]]],





         [[[[[[0., 1.],
              [1., 0.]],

             [[1., 0.],
              [0., 1.]]],


            [[[1., 0.],
              [0., 1.]],

             [[0.,

将变量 y_train 和 y_test 中得到的整数转换为独热编码版本，to_categorical()用于将整数编码的类别标签y = [0, 1, 2, 3]转换为独热编码，[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]



In [28]:
number_of_classes = 1.00 + max(np.append(y_train, y_test))
#合并输入列表以找到其中的最大值，然后添加 1
y_train = to_categorical(y_train, num_classes=number_of_classes)
y_test = to_categorical(y_test, num_classes=number_of_classes)
#将每个列表编码为我们刚刚找到的大小的独热数组

TypeError: 'numpy.float64' object cannot be interpreted as an integer

了确保任何两个标签列表的编码大小相同，我们将把所有标签合并为一个大列表
并提取其最大值。由于我们从 0 开始，我们将在结果中添加 1，这是可以对所有标
签中的所有值进行编码的列表的最小大小。

如果将 y_train 和 y_test 依次传递给to_categorical() 并继续，则如果测试和训练两个表的类别有可能不同，训练有10个类别，测试有9个，从而导致列表大小不同，2者无法比较。用to_categorial()的参数num_classes强行制定最大类。

In [29]:
one_hot = [0, 0, 0, 1, 0, 0, 0, 0, 0, 0]
print("one-hot 表示整数 ",one_hot.index(1))
#使用 Python 的 index() 方法“撤消”独热编码

one-hot represents the integer  3


In [32]:
one_hot_np = np.array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0])
print("one_hot_np 表示整数 ",np.argmax(one_hot_np))
#NumPy 的 argmax() 方法，该方法返回列表中最大值的索引

one_hot_np represents the integer  3


In [33]:
original_y_train = y_train
original_y_test = y_test
original_y_train = [np.argmax(v) for v in y_train]
original_y_test = [np.argmax(v) for v in y_test]
#独热编码目标重新转换为整数列表

由于独热编码非常常见，scikit-learn 还提供了一个工具来执行它。它位于预处
理模块中，名为 OneHotEncoder()。我们首先读取（并可能下载）MNIST 数据，然后为 Keras 准备每幅图
像，将其从整数更改为浮点数，然后对其进行归一化。然后我们创建标签的独热编
码。