<a href="https://colab.research.google.com/github/x200168shen/Cookbook-for-Rustaceans-in-Finance/blob/main/BERAS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
demoDate = np.array( [[1,2,3,4],[5,6,7,8],[9,10,11,12]])
newDate = np.reshape(demoDate,(6,2))
print(newDate)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [ ]:
from tensorflow.keras.datasets import mnist
(samples_train, labels_train), (samples_test, labels_test) = \
   mnist.load_data()

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


MNIST集是 Keras 提供的。我们导入 mnist 模块，然后使用其定义的 load_data() 返回1训练集和1测试集,注意\后面没有空格，然后开始下载集，并存到磁盘上，速度很快

In [ ]:
print("samples_train shape = ",samples_train.shape)
print("labels_train shape = ",labels_train.shape)
print("samples_test shape = ",samples_test.shape)
print("labels_test shape = ",labels_test.shape)

samples_train shape =  (60000, 28, 28)
labels_train shape =  (60000,)
samples_test shape =  (10000, 28, 28)
labels_test shape =  (10000,)


第一对变量 samples_train 和 labels_train 保存了包含训练集的 60,000
张图像及其对应的整数标签的数组。第二对变量 samples_test 和 labels_test 保存了包含测试集的 10,000 张图像和标签的数组。打印它们来快速查看它们的形状。这些数组都是从 Keras 返回的 NumPy 数组，因此它们都具有我们可以打印的内置 shape 属性。array（）的作用，6000逗号表示是列表而不是数字

In [1]:
from tensorflow.keras.datasets import mnist
(X_train, y_train), (X_test, y_test) = \
   mnist.load_data()

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


惯例是使用大写字母 X 来指代数据集的样本，使用小写字母 y 来指代其标签,加载 MNIST 数据，使用 X 作为样本，y 作为标签

In [3]:
image_height = X_train.shape[1]
image_width = X_train.shape[2]
number_of_pixels = image_height * image_width

因此让我们将每幅图像的原始高度和宽度存储在一个
变量中。我们还将它们相乘并将其保存为每幅图像的总像素数,这
种更通用的方法将使以后复制此代码并使其适应新的数据集变得更容易

In [4]:
print('start of y_train:', y_train[:15])

start of y_train: [5 0 4 1 9 2 1 3 1 4 3 5 3 6 1]


数据集中前15个元素

图像匹配。
由于 MNIST 数据非常知名，我们可以就此停止，但对于不太熟悉的数据集，我们可
能需要在整个数据中进行至少几次这样的抽查，以确保两个列表保持同步

In [5]:
X_train[0, 5:12, 5:12]

array([[  0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,  30,  36,  94, 154],
       [  0,   0,  49, 238, 253, 253, 253],
       [  0,   0,  18, 219, 253, 253, 253],
       [  0,   0,   0,  80, 156, 107, 253],
       [  0,   0,   0,   0,  14,   1, 154],
       [  0,   0,   0,   0,   0,   0, 139]], dtype=uint8)

末尾的变量 dtype 告诉我们这是一个 NumPy 数组，由数据类型 uint8 表示，这意味
着一个无符号的 8 位整数。检查 X_test 会发现相同的结构。正如我们从灰度图像数
据中预期的那样，所有值都在 0 到 255 之间

In [6]:
y_train[:15]


array([5, 0, 4, 1, 9, 2, 1, 3, 1, 4, 3, 5, 3, 6, 1], dtype=uint8)

无符号 8 位整数的 1D NumPy 数组，对于训练标签来说非常严格，
因为这些数字不能超过 255。但这里我们只存储标签 0 到 9，所以 0 到 255 的范围足
够了。

In [13]:
from sklearn.model_selection import train_test_split
 X_train, X_test, y_train, y_test  = \
  train_test_split(samples, labels, test_size=0.25)

NameError: name 'samples' is not defined

In [14]:
from tensorflow.keras import backend as keras_backend
X_train = keras_backend.cast_to_floatx(X_train)
X_test = keras_backend.cast_to_floatx(X_test)

遍历每个条目并将其转换为我们所需的数据类型,Keras 后端的 cast_to_floatx() 函数，该函数以张量为参数，并将该张量的每个元素转换为 floatx 当前值指定的类型。该例程甚至不关心张量的形状。从一维列表到一些巨大的

In [17]:
import numpy as np
X_train = np.interp(X_train, [0, 255], [0,1])
X_test = np.interp(X_test, [0, 255], [0,1])
X_train /= 255.0
X_test /= 255.0

X_train 和 X_test 中的特征数据最初由 0 到 255 范围内的
整数组成，这是图像数据通道的常见范围。我们刚刚将这些值转换为 32 位浮点
数，因此我们可以说它们现在在 0.0 到 255.0 范围内。
我们上面说过，我们需要将数据标准化到 [0.0, 1.0] 范围内。正如我们在前几章中看
到的，这有助于将神经元输出保持在同一范围内，从而有助于正则化并延迟过度拟
合的发生。如果我们使用像 S 型这样的激活函数，它可以防止我们的函数饱和。
我们可以通过完整的预处理步骤来实现这种规范化。我们将检查训练数据中像素的
值，构建一个转换以将它们缩放到 [0,1]，然后将该转换应用于训练数据、测试数据
和任何未来数据。我们可以创建一个 scikit-learn 的转换对象，对其进行训练，然后
将其应用于我们的数据。使用 Numpy 的 interp() 例程来缩放输入数据，该例程就是为这项工作而设
计的。它需要一个数组（或张量）、一个输入范围和一个输出范围,将所有像素除以255.0来实现同样的事情